apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rr7vzkimq-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rr7vzkimq-java-springboot-gitops